name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build the site
        run: |
          echo "Building site..."
          # Example for static HTML site:
          mkdir dist
          cp -r * dist || true
          rm -rf dist/.git dist/.github

      - name: Deploy to github.io repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: notyourimaginarycoder/notyourimaginarycoder.github.io
          publish_branch: main
          publish_dir: ./dist
